Bookers/config/routes.rb
Rails.application.routes.draw do
  root to: 'books#top'
  get 'books' => 'books#index'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as:'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers/app/models/book.rb
class Book < ApplicationRecord
  validates :title, 
    presence: true
  validates :body, 
    presence: true
end

Bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def top
  end

  def index
    @book = Book.new
    @books = Book.all
  end
  
  def show
    @book = Book.find(params[:id])
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id), notice: 'Book was successfully created.'
    else
      @books = Book.all
      render :index    
    end
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'Book was successfully created.'
    else
      @books = Book.all
      render action: :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
end

Bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers/app/helpers/books_helper.rb
module BooksHelper
end

Bookers/app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>

<% if @book.errors.any? %>
<%= @book.errors.count %>errors prohibited this book from being saved:
  <div class = "alert">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %><br>
  <%= f.submit 'Update Book'%><br>
  
<%= link_to "Show", book_path(@book.id) %>
<span>|</span>
<a href="/books">Back</a>
<% end %>

Bookers/app/views/books/index.html.erb
<h1>Books</h1>
 
<table>
<tr>
  <th>Title</th>
  <th>Body</th> 
</tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>
    <td><%= link_to "Show", book_path(book.id) %></td>
    <td><%= link_to "Edit", edit_book_path(book.id) %></td>
    <td><%= link_to"Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
  </tr>
<% end %>
</table>

<h3>New book</h3>

<%= form_with model:@book, local:true do |f| %>

<% if @book.errors.any? %>
<%= @book.errors.count %>errors prohibited this book from being saved:
  <div class = "alert">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <div class="submit_box">
  <p>Title</p>
  <%= f.text_field :title %>
  <p>Body</p>
  <%= f.text_area :body %>
  <br><%= f.submit 'Create Book' %></div>
<% end %>

Bookers/app/views/books/new.html.erb
<h1>Books</h1>

<h3>New book</h3>
<%= form_with model:@book, local:true do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>
  
  <%= f.submit 'Create Book' %>

<% end %>

Bookers/app/views/books/show.html.erb
<p id="notice">
    <%= notice %></p>
<p><strong>Title:</strong>
<%= @book.title %></p>
<p><strong>Body:</strong>
<%= @book.body %></p><br>

<%= link_to "Edit", edit_book_path(@book.id) %>
<span>|</span>
<a href="/books">Back</a>

Bookers/app/views/books/top.html.erb
<head>
  <title>WebCampBackendNew</title>
</head>
<body>
    <h2>ようこそBookersへ！</h2>
    <p class="comment">Bookersではさまざまな書籍に関するあなたの意見や</p>
    <p class="comment">印象を共有し交換することができます</p>
    <a href="/books">start</a>
</body>

Bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>